name: check_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - pandas=1.5.3
  - pip=24.0
  - pytest=7.4.0
  - scipy=1.9.3
  - pip:
      - wandb==0.17.4
      - numpy==1.24.4
      - databricks-cli==0.18.0